# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Disable layout cops that conflict with Prettier formatting
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false
